name: Build .NET Windows App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Run unit tests (if any)
      run: dotnet test --no-build --configuration Release
      continue-on-error: true  # Optional: allow workflow to continue even if tests fail

    - name: Publish (portable exe)
      run: dotnet publish -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -o publish

    - name: Upload published app
      uses: actions/upload-artifact@v4
      with:
        name: PublishedApp
        path: publish
